package de.dhbw.karlsruhe.turniere.services;

import de.dhbw.karlsruhe.turniere.database.models.Group;
import de.dhbw.karlsruhe.turniere.database.models.GroupStage;
import de.dhbw.karlsruhe.turniere.database.models.Match;
import de.dhbw.karlsruhe.turniere.database.models.Team;
import de.dhbw.karlsruhe.turniere.database.models.Tournament;
import de.dhbw.karlsruhe.turniere.database.repositories.GroupRepository;
import de.dhbw.karlsruhe.turniere.database.repositories.GroupStageRepository;
import de.dhbw.karlsruhe.turniere.database.repositories.MatchRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
@RequiredArgsConstructor
public class GroupStageService {

    private final GroupStageRepository groupStageRepository;
    private final GroupRepository groupRepository;
    private final MatchRepository matchRepository;

    /**
     * Generates and fills the GroupStage (with given groupSize) of given tournament and adds it to given owner
     *
     * @param origTeams  List of Teams to generate GroupStage with
     * @param tournament Tournament to add GroupStage to
     * @param groupSize  Size of the given Groups
     * @return Generated GroupStage populated with Groups and Matches
     */
    public GroupStage generateGroupStage(List<Team> origTeams, Tournament tournament, Integer groupSize) {
        List<Team> teams = new ArrayList<>(origTeams);
        int requiredGroupCount = teams.size() / groupSize;
        List<Group> groups = new ArrayList<>();
        //first group Name
        char name = 'A';

        //iterate through number of groups
        for (int i = 0; i < requiredGroupCount; i++) {
            groups.add(new Group((char) ((int) name + i)));
            List<Team> groupTeams = new ArrayList<>();
            //generate list of teams to add to group
            for (int j = 0; j < origTeams.size() / requiredGroupCount; j++) {
                groupTeams.add(teams.get(0));
                teams.remove(0);
            }
            //add teams to group
            groups.get(i).setTeams(groupTeams);
            //add matches between all teams to group
            groups.get(i).setMatches(generateAllPossibleMatches(groupTeams));
        }
        //save everything in database
        Iterable<Group> savedGroupsIterable = groupRepository.saveAll(groups);
        List<Group> savedGroups = new ArrayList<>();
        savedGroupsIterable.forEach(savedGroups::add);
        GroupStage groupStage = new GroupStage(savedGroups);
        groupStage = groupStageRepository.save(groupStage);
        tournament.setGroupStage(groupStage);

        return groupStage;
    }

    /**
     * Generates all possible Matchups between given Teams
     *
     * @param origTeams Teams to generate Matches with
     * @return List of Matches containing all possible Matchups of given Teams
     */
    private List<Match> generateAllPossibleMatches(List<Team> origTeams) {
        List<Match> matches = new ArrayList<>();
        List<Team> teams = new ArrayList<>(origTeams);
        //initial position of first match
        int position = 0;

        int cycle = teams.size();
        //iterates through all teams
        for (int i = 0; i < cycle; i++) {
            Team team1 = teams.get(0);
            //iterates through all teams except first
            for (int j = 1; j < teams.size(); j++) {
                Team team2 = teams.get(j);
                //add match to list with every combination of teams
                matches.add(new Match(team1, team2, null, null, Match.State.NOT_STARTED, position++));
            }
            //remove first team from list since all games for this team are generated by now
            teams.remove(0);
        }

        //save everything to database
        Iterable<Match> savedMatchesIterable = matchRepository.saveAll(matches);
        List<Match> savedMatches = new ArrayList<>();
        savedMatchesIterable.forEach(savedMatches::add);

        return matches;
    }
}
