package de.dhbw.karlsruhe.turniere.services;

import de.dhbw.karlsruhe.turniere.database.models.Group;
import de.dhbw.karlsruhe.turniere.database.models.GroupStage;
import de.dhbw.karlsruhe.turniere.database.models.Match;
import de.dhbw.karlsruhe.turniere.database.models.Team;
import de.dhbw.karlsruhe.turniere.database.models.Tournament;
import de.dhbw.karlsruhe.turniere.database.repositories.GroupRepository;
import de.dhbw.karlsruhe.turniere.database.repositories.GroupStageRepository;
import de.dhbw.karlsruhe.turniere.database.repositories.MatchRepository;
import de.dhbw.karlsruhe.turniere.database.repositories.TeamRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import static java.util.Comparator.comparing;
import static java.util.Comparator.comparingInt;
import static java.util.stream.Collectors.toList;

@Component
@RequiredArgsConstructor
public class GroupStageService {

    private final GroupStageRepository groupStageRepository;
    private final MatchService matchService;
    private final GroupRepository groupRepository;
    private final MatchRepository matchRepository;
    private final TeamRepository teamRepository;
    private final PlayoffService playoffService;

    /**
     * Generates and fills the GroupStage (with given groupSize) of given tournament and adds it to given owner
     *
     * @param origTeams  List of Teams to generate GroupStage with
     * @param tournament Tournament to add GroupStage to
     * @param groupSize  Size of the given Groups
     * @return Generated GroupStage populated with Groups and Matches
     */
    public GroupStage generateGroupStage(List<Team> origTeams, Tournament tournament, Integer groupSize, int playoffSize) {
        List<Team> teams = new ArrayList<>(origTeams);
        int requiredGroupCount = teams.size() / groupSize;
        List<Group> groups = new ArrayList<>();
        //first group Name
        int name = 1;

        //iterate through number of groups
        for (int i = 0; i < requiredGroupCount; i++) {
            groups.add(new Group(Integer.toString(name + i), i));
            List<Team> groupTeams = new ArrayList<>();
            //generate list of teams to add to group
            for (int j = 0; j < origTeams.size() / requiredGroupCount; j++) {
                groupTeams.add(teams.get(0));
                teams.remove(0);
            }
            //add teams to group
            groups.get(i).setTeams(groupTeams);
            //add matches between all teams to group
            groups.get(i).setMatches(generateAllPossibleMatches(groupTeams));
        }
        //save everything in database
        Iterable<Group> savedGroupsIterable = groupRepository.saveAll(groups);
        List<Group> savedGroups = new ArrayList<>();
        savedGroupsIterable.forEach(savedGroups::add);
        GroupStage groupStage = new GroupStage(savedGroups);
        groupStage.setPlayoffSize(playoffSize);
        groupStage = groupStageRepository.save(groupStage);
        tournament.setGroupStage(groupStage);
        tournament.setCurrentStage("groupStage");

        return groupStage;
    }

    /**
     * Generates all possible Matchups between given Teams
     *
     * @param origTeams Teams to generate Matches with
     * @return List of Matches containing all possible Matchups of given Teams
     */
    private List<Match> generateAllPossibleMatches(List<Team> origTeams) {
        List<Match> matches = new ArrayList<>();
        List<Team> teams = new ArrayList<>(origTeams);
        //initial position of first match
        int position = 0;

        int cycle = teams.size();
        //iterates through all teams
        for (int i = 0; i < cycle; i++) {
            Team team1 = teams.get(0);
            //iterates through all teams except first
            for (int j = 1; j < teams.size(); j++) {
                Team team2 = teams.get(j);
                //add match to list with every combination of teams
                matches.add(new Match(team1, team2, 0, 0, Match.State.NOT_STARTED, position++, true));
            }
            //remove first team from list since all games for this team are generated by now
            teams.remove(0);
        }

        if (origTeams.size() == 4) {
            //ugly but working
            Collections.swap(matches, 1, 5);
            matches.get(1).setPosition(1);
            matches.get(5).setPosition(5);
        }

        //save everything to database
        Iterable<Match> savedMatchesIterable = matchRepository.saveAll(matches);
        List<Match> savedMatches = new ArrayList<>();
        savedMatchesIterable.forEach(savedMatches::add);

        return matches;
    }

    /**
     * Updates a Teams points and Table in GroupStage
     *
     * @param team The Team to update the Points for
     */
    public void updateTeamPoints(Team team) {
        //get the Teams Group
        Group group = groupRepository.findByTeamsContains(team);
        //get all Teams of Group
        List<Team> allTeams = group.getTeams();
        //get all Matches of the Team
        List<Match> allMatches = group.getMatches().stream().filter(match -> match.getTeam1().equals(team) || match.getTeam2().equals(team)).collect(toList());
        //initialize Variables
        int pointsRecieved = 0;
        int pointsScored = 0;
        int score = 0;
        //iterate over all Matches
        for (Match match : allMatches) {
            Match.State matchState;
            //Set matchState to actual live State
            if (match.getState() == Match.State.IN_PROGRESS) {
                //If Match is IN_PROGRESS Winner is evaluated (Match is not over yet, this is just for Live Scores)
                matchState = matchService.evaluateWinner(match);
            } else {
                //If Match is Over The State is just read out of it
                matchState = match.getState();
            }
            //evaluate Points of the Team for the Match
            if (match.getTeam1() == team) {
                pointsScored = pointsScored + match.getScoreTeam1();
                pointsRecieved = pointsRecieved + match.getScoreTeam2();
                //Give Points for winning and draws
                if (matchState == Match.State.TEAM1_WON) {
                    score = score + 1;
                } else if (matchState == Match.State.UNDECIDED) {
                    score = score + 0;
                }
            } else if (match.getTeam2() == team) {
                pointsRecieved = pointsRecieved + match.getScoreTeam1();
                pointsScored = pointsScored + match.getScoreTeam2();
                //Give Points for winning and draws
                if (matchState == Match.State.TEAM2_WON) {
                    score = score + 1;
                } else if (matchState == Match.State.UNDECIDED) {
                    score = score + 0;
                }

            }

        }
        //Give Team its Scores
        team.setGroupPointsReceived(pointsRecieved);
        team.setGroupPointsScored(pointsScored);
        team.setGroupScore(score);
        //Remove GroupPlace for all Teams for sorting
        int allTeamsSize = allTeams.size();
        for (int i = 0; i < allTeamsSize; i++) {
            allTeams.get(i).setGroupPlace(0);
        }
        sortTeams(allTeams);
        //Set GroupPlace for the Teams according to the sorted List
        for (int i = 0; i < allTeamsSize; i++) {
            allTeams.get(i).setGroupPlace(i);
        }
        //save to Database
        teamRepository.saveAll(allTeams);
    }

    /**
     * Sorts the Teams by GroupPlace,GroupScore,GroupPointsScored and GroupPointsRecieved.
     *
     * @param teams List of Teams to sort
     * @return Sorted List of Teams
     */
    public List<Team> sortTeams(List<Team> teams) {
        //sort Teams by GroupPlace (lower is better)
        teams.sort(Comparator
                // by GroupPlace (to sort quicker when nothing changed)
                .comparingInt(Team::getGroupPlace)
                // by GroupScore (higher is better)
                .thenComparing(comparing(Team::getGroupScore).reversed())
                // by Group Points difference
                .thenComparing((o1, o2) -> {
                    int result1 = o1.getGroupPointsScored() - o1.getGroupPointsReceived();
                    int result2 = o2.getGroupPointsScored() - o2.getGroupPointsReceived();
                    if (result1 < result2) {
                        return 1;
                    } else if (result1 > result2) {
                        return -1;
                    } else {
                        return 0;
                    }
                })
                // by GroupPointsScored (higher is better)
                .thenComparing(comparing(Team::getGroupPointsScored).reversed())
                // by GroupPointsRecieved (lower is better)
                .thenComparing(Team::getGroupPointsReceived));
        return teams;
    }

    /**
     * Given the GroupStage, return the List of Teams that Advance to Playoffs
     *
     * @param groupStage The Groupstage to get the Playoff Teams from
     * @return List of Teams that advance to Playoffs
     */
    public List<Team> getPlayoffTeams(GroupStage groupStage) {
        List<Team> playoffTeams = new ArrayList<>();
        List<Group> groups = groupStage.getGroups();
        int groupNumber = groups.size();
        int groupSize = groups.get(0).getTeams().size();
        int playoffSize = groupStage.getPlayoffSize();

        Double howManyPlacesFitDouble = (double) playoffSize / groupNumber;
        int howManyPlacesFitInt = howManyPlacesFitDouble.intValue();

        for (int j = 0; j < howManyPlacesFitInt; j++) {
            for (int i = 0; i < groupNumber; i++) {
                List<Team> teamsOfGroup = groups.get(i).getTeams();
                teamsOfGroup.sort(Comparator.comparingInt(Team::getGroupPlace));
                Team team = teamsOfGroup.get(j);
                playoffTeams.add(team);
            }
        }
        if (playoffTeams.size() != playoffSize) {
            List<Team> remainingTeams = new ArrayList<>();
            for (int i = 0; i < groupNumber; i++) {
                remainingTeams.add(groups.get(i).getTeams().get(howManyPlacesFitInt));
            }
            sortTeams(remainingTeams);

            int remainingTeamsNeeded = playoffSize - playoffTeams.size();
            for (int i = 0; i < (remainingTeamsNeeded); i++) {
                playoffTeams.add(remainingTeams.get(i));
            }

        }

        return playoffTeams;
    }

    /**
     * Checks if all Groups in given GroupStage are finished
     *
     * @param groupStage GroupStage to check
     * @return true when all Groups finished
     */
    public Boolean isGroupStageOver(GroupStage groupStage) {
        for (Group group : groupStage.getGroups()) {
            if (!isGroupOver(group)) {
                return false;
            }
        }
        return true;
    }

    /**
     * Checks if given Group finished all Matches
     *
     * @param group The Group to check
     * @return true when all Matches finished
     */
    public Boolean isGroupOver(Group group) {
        for (Match match : group.getMatches()) {
            Match.State state = match.getState();
            if (state == Match.State.NOT_STARTED || state == Match.State.IN_PROGRESS) {
                return false;
            }
        }
        return true;
    }

}
